name: coverage

on:
  pull_request:
  push:
    branches:
      - main


jobs:
  test:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml # optional
          files: ./coverage1.xml,./coverage2.xml # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
